name: master

on:
  pull_request:
    paths:
      - crates/**
      - "!**/*.md"
      - "!.github/screenshots/**"
  push:
    branches: [master]
    paths:
      - Dockerfile
      - crates/**
      - "!**/*.md"
      - "!.github/screenshots/**"
      - ".github/workflows/**"

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.13.1/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C $HOME/.cargo/bin
          chmod +x $HOME/.cargo/bin/trunk
      - name: Install wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Build tanoshi-web
        run: cd crates/tanoshi-web && trunk build --release
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: crates/tanoshi-web/dist
  build-docker:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: default
    needs:
      - build-web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: crates/tanoshi-web/dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir crates/tanoshi-web/dist
      - name: Install deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y libssl-dev libarchive-dev build-essential cmake llvm clang libicu-dev nettle-dev libacl1-dev liblzma-dev libzstd-dev liblz4-dev libbz2-dev zlib1g-dev libxml2-dev
      - name: Install deps
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install icu4c libarchive bzip2 lz4 zlib expat
      - name: Install LLVM and Clang
        if: ${{ matrix.os == 'windows-latest' }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.1"
      - name: Cache vcpkg
        uses: actions/cache@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: "C:/vcpkg/installed"
          key: vcpkg-${{ matrix.os }}-
          restore-keys: |
            vcpkg-${{ matrix.os }}-
      - name: Install deps
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          vcpkg integrate install
          vcpkg install --only-downloads libarchive:x64-windows-static-md
          vcpkg install libarchive:x64-windows-static-md
      - name: Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig
      - name: Test
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          LIBCLANG_PATH: C:\Program Files\LLVM\bin
